# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: 'Home',               url: 'facts'}
- {name: 'About',              url: 'about'}
- {name: 'Who is the Actuary?', url: 'resources'}
# Don't need Sample Posts for now
- {name: 'Sample Posts',       url: 'sample-posts'}
- {name: 'Join Us!',      url: 'documentation'}
- {name: 'Contact',            url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
# TODO need to change to club linkedin
- {icon: 'linkedin', link:    'https://www.linkedin.com/in/noah-ford-79a0a223b/'}
# - {icon: 'facebook', link:   'https://www.facebook.com/paululele'}
- {icon: 'instagram', link:  'https://instagram.com/paululele'}
- {icon: 'envelope', link:   'mailto:umass.gis@gmail.com'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
